/**
 * Copyright (C) 2013 Sébastien Lesaint (http://www.javatronic.fr/)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *         http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package fr.javatronic.damapping.intellij.plugin.integration.cache;

import fr.javatronic.damapping.intellij.plugin.integration.component.project.ParseAndGenerateManager;
import fr.javatronic.damapping.intellij.plugin.integration.index.GeneratedClassSimpleNameIndex;

import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import com.intellij.openapi.project.Project;
import com.intellij.openapi.vfs.VirtualFile;
import com.intellij.psi.PsiClass;
import com.intellij.psi.PsiField;
import com.intellij.psi.PsiFile;
import com.intellij.psi.PsiJavaFile;
import com.intellij.psi.PsiManager;
import com.intellij.psi.PsiMethod;
import com.intellij.psi.search.GlobalSearchScope;
import com.intellij.psi.search.PsiShortNamesCache;
import com.intellij.util.Processor;
import com.intellij.util.containers.HashSet;
import com.intellij.util.indexing.FileBasedIndex;
import org.jetbrains.annotations.NonNls;
import org.jetbrains.annotations.NotNull;

/**
 * DAMappingPsiShortNamesCache -
 *
 * @author Sébastien Lesaint
 */
public class DAMappingPsiShortNamesCache extends PsiShortNamesCache {

  private static final PsiMethod[] NO_PSI_METHODS = new PsiMethod[0];
  private static final PsiField[] NO_PSI_FIELDS = new PsiField[0];
  private static final String[] NO_NAMES = new String[0];

  private final Project project;

  public DAMappingPsiShortNamesCache(Project project) {
    this.project = project;
  }

  /**
   * Retrieves the PsiClass of a class generated by DAMapping by its name.
   * This method relies on the GeneratedClassSimpleNameIndex to quickly tell if the specified name is the name of a
   * class generated by DAMapping. If so, it uses
   * {@link ParseAndGenerateManager#getGeneratedPsiClasses(com.intellij.psi.PsiClass, com.intellij.psi.search.GlobalSearchScope)}
   * to retrieve the PsiClass of the requested name.
   */
  @NotNull
  @Override
  public PsiClass[] getClassesByName(@NotNull @NonNls String name, @NotNull GlobalSearchScope scope) {
    ParseAndGenerateManager parseAndGenerateManager = ParseAndGenerateManager.getInstance(project);
    Collection<VirtualFile> files = FileBasedIndex.getInstance()
                                               .getContainingFiles(GeneratedClassSimpleNameIndex.NAME, name, scope);
    for (VirtualFile file : files) {
      PsiManager psiManager = PsiManager.getInstance(project);
      PsiFile psiFile = psiManager.findFile(file);
      if (psiFile instanceof PsiJavaFile) {
        PsiClass psiClass = ((PsiJavaFile) psiFile).getClasses()[0];
        List<PsiClass> generatedPsiClasses = parseAndGenerateManager.getGeneratedPsiClasses(psiClass, scope);
        for (PsiClass generatedPsiClass : generatedPsiClasses) {
          if (name.equals(generatedPsiClass.getName())) {
            return new PsiClass[] {generatedPsiClass};
          }
        }
      }
    }

    return PsiClass.EMPTY_ARRAY;
  }

  /**
   * Returns an array of the names of all the classes/interfaces generated by DAMapping in the current project.
   * This method relies on the {@link GeneratedClassSimpleNameIndex} to nuild the collection of PsiClass name
   * efficiently.
   */
  @NotNull
  @Override
  public String[] getAllClassNames() {
    Collection<String> allKeys = FileBasedIndex.getInstance().getAllKeys(GeneratedClassSimpleNameIndex.NAME, project);
    return allKeys.toArray(new String[allKeys.size()]);
  }

  @Override
  public void getAllClassNames(@NotNull HashSet<String> dest) {
    dest.addAll(Arrays.asList(getAllClassNames()));
  }

  @NotNull
  @Override
  public PsiMethod[] getMethodsByName(@NonNls @NotNull String name, @NotNull GlobalSearchScope scope) {
    return NO_PSI_METHODS;
  }

  @NotNull
  @Override
  public PsiMethod[] getMethodsByNameIfNotMoreThan(@NonNls @NotNull String name, @NotNull GlobalSearchScope scope,
                                                   int maxCount) {
    return NO_PSI_METHODS;
  }

  @NotNull
  @Override
  public PsiField[] getFieldsByNameIfNotMoreThan(@NonNls @NotNull String name, @NotNull GlobalSearchScope scope,
                                                 int maxCount) {
    return NO_PSI_FIELDS;
  }

  @Override
  public boolean processMethodsWithName(@NonNls @NotNull String name, @NotNull GlobalSearchScope scope,
                                        @NotNull Processor<PsiMethod> processor) {
    return false;
  }

  @NotNull
  @Override
  public String[] getAllMethodNames() {
    return NO_NAMES;
  }

  @Override
  public void getAllMethodNames(@NotNull HashSet<String> set) {
    // do nothing -- not supported
  }

  @NotNull
  @Override
  public PsiField[] getFieldsByName(@NotNull @NonNls String name, @NotNull GlobalSearchScope scope) {
    return NO_PSI_FIELDS;
  }

  @NotNull
  @Override
  public String[] getAllFieldNames() {
    return NO_NAMES;
  }

  @Override
  public void getAllFieldNames(@NotNull HashSet<String> set) {
    // do nothing -- not supported
  }
}
